version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concesionario
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: concesionario
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  db_data:
